name: Build and Deploy IPFS WebUI

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build WebUI
        run: npm run build

      - name: Copy built files to nginx webroot
        run: |
          sudo rm -rf /var/www/ipfs-webui
          sudo mkdir -p /var/www/ipfs-webui
          sudo cp -r build/* /var/www/ipfs-webui/
